using SotsRestApi.Models;
using System;
using System.Collections.Generic;

namespace SotsRestApi.DAL
{
    public class SotsInitializer : System.Data.Entity.DropCreateDatabaseAlways<SotsContext>
    {
        protected override void Seed(SotsContext context)
        {
            List<Student> students = new List<Student>
            {
                new Student{FirstName="Patryk", LastName="Kopeć", AlbumNo=265663, ActualSemester=5, Login="patkop", Password="123", CourseID=1 },
                new Student{FirstName="Maciej", LastName="Małek", AlbumNo=265675, ActualSemester=5, Login="macmal", Password="123", CourseID=1 },
                new Student{FirstName="Patryk", LastName="Olszowy", AlbumNo=265432, ActualSemester=5, Login="patols", Password="123", CourseID=1 },
                new Student{FirstName="Maciej", LastName="Stolarczyk", AlbumNo=242132, ActualSemester=5, Login="macsto", Password="123", CourseID=1 },
                new Student{FirstName="Wiktor", LastName="Pastwa", AlbumNo=242145, ActualSemester=4, Login="wikpas", Password="123", CourseID=1 },

                new Student{FirstName="Maciej", LastName="Mazur", AlbumNo=242356, ActualSemester=5, Login="macmaz", Password="123", CourseID=1 },
                new Student{FirstName="Patryk", LastName="Pietrasiak", AlbumNo=265879, ActualSemester=5, Login="patpie", Password="123", CourseID=1 },
                new Student{FirstName="Paweł", LastName="Grabowski", AlbumNo=243478, ActualSemester=5, Login="pawgra", Password="123", CourseID=1 },
                new Student{FirstName="Dominik", LastName="Lorke", AlbumNo=265676, ActualSemester=5, Login="domlor", Password="123", CourseID=1 },
                new Student{FirstName="Jakub", LastName="Cieśliński", AlbumNo=265665, ActualSemester=5, Login="jakcie", Password="123", CourseID=1 },

                new Student{FirstName="Marcin", LastName="Budziosz", AlbumNo=264879, ActualSemester=5, Login="marbud", Password="123", CourseID=1 },
                new Student{FirstName="Mateusz", LastName="Rugor", AlbumNo=266123, ActualSemester=5, Login="matrug", Password="123", CourseID=1 },
                new Student{FirstName="Rafał", LastName="Faruga", AlbumNo=266432, ActualSemester=5, Login="raffar", Password="123", CourseID=1 },
                new Student{FirstName="Mateusz", LastName="Gołas", AlbumNo=255432, ActualSemester=5, Login="matgol", Password="123", CourseID=1 },
                new Student{FirstName="Dawid", LastName="Załużny", AlbumNo=265389, ActualSemester=5, Login="dawzal", Password="123", CourseID=1 },

                new Student{FirstName="Mirosław", LastName="Kusiek", AlbumNo=266476, ActualSemester=5, Login="mirkus", Password="123", CourseID=1 },
            };

            students.ForEach(s => context.Student.Add(s));
            context.SaveChanges();
            List<Course> courses = new List<Course>
            {
                new Course {Name="Informatyka"},
                new Course {Name="Elektronika"},
                new Course {Name="Energetyka"},
                new Course {Name="Mechatronika"},
                new Course {Name="Elektrotechnika"}
            };

            courses.ForEach(c => context.Course.Add(c));
            context.SaveChanges();
            List<Class> classes = new List<Class>
            {
                new Class{Name="Programowanie Mikrokontrolerów", ECTSValue=3, CourseID=1, SemesterID=5,TeacherID=1},
                new Class{Name="Podstawy Programowania", ECTSValue=5, CourseID=1, SemesterID=1, TeacherID=2},
                new Class{Name="Elektronika", ECTSValue=4, CourseID=1, SemesterID=2, TeacherID=3},
                new Class{Name="Obwody Elektryczne", ECTSValue=6, CourseID=1, SemesterID=1, TeacherID=4},
                new Class{Name="Analogowe Przetwarzanie Sygnałów", ECTSValue=5, CourseID=1, SemesterID=2, TeacherID=4},

                new Class{Name="Technika Inżynierska I", ECTSValue=2, CourseID=1, SemesterID=1, TeacherID=6},
                new Class{Name="Technika Inżynierska II", ECTSValue=3, CourseID=1, SemesterID=1, TeacherID=5},
                new Class{Name="Metrologia", ECTSValue=1, CourseID=1, SemesterID=1, TeacherID=7},
                new Class{Name="Measurment Science", ECTSValue=1, CourseID=1, SemesterID=1, TeacherID=7},
                new Class{Name="Technika Inżynierska I", ECTSValue=2, CourseID=1, SemesterID=1, TeacherID=5},

                new Class{Name="Matematyka I", ECTSValue=5, CourseID=1, SemesterID=1, TeacherID=8},
                new Class{Name="Matematyka II", ECTSValue=4, CourseID=1, SemesterID=1, TeacherID=10},
                new Class{Name="Fizyka", ECTSValue=6, CourseID=1, SemesterID=1, TeacherID=9},
                new Class{Name="Systemy Operacyjne", ECTSValue=4, CourseID=1, SemesterID=2, TeacherID=11},
                new Class{Name="Programowanie Obiektowe", ECTSValue=6, CourseID=1, SemesterID=2, TeacherID=12},

                new Class{Name="Obwody Elektryczne", ECTSValue=1, CourseID=1, SemesterID=2, TeacherID=4},
                new Class{Name="Metrologia", ECTSValue=1, CourseID=1, SemesterID=2, TeacherID=7},
                new Class{Name="Matematyka III", ECTSValue=4, CourseID=1, SemesterID=2, TeacherID=10},
                new Class{Name="Fizyka", ECTSValue=3, CourseID=1, SemesterID=2, TeacherID=9},
                new Class{Name="Algorytmy i struktury danych", ECTSValue=2, CourseID=1, SemesterID=2, TeacherID=13},

                new Class{Name="Wychowanie Fizyczne", ECTSValue=1, CourseID=1, SemesterID=3, TeacherID=14},
                new Class{Name="Technika Cyfrowa", ECTSValue=3, CourseID=1, SemesterID=3, TeacherID=15},
                new Class{Name="Systemy Informacyjne", ECTSValue=2, CourseID=1, SemesterID=3, TeacherID=15},
                new Class{Name="Sieci Komputerowe", ECTSValue=4, CourseID=1, SemesterID=3, TeacherID=15},
                new Class{Name="Programowanie w Systemach Sterowania", ECTSValue=3, CourseID=1, SemesterID=3, TeacherID=16},

                new Class{Name="Programowanie Interfejsu Użytkownika", ECTSValue=4, CourseID=1, SemesterID=3, TeacherID=2},
                new Class{Name="Prawo Własności Intelektualnej i Internetu", ECTSValue=3, CourseID=1, SemesterID=3, TeacherID=17},
                new Class{Name="Język Angielski", ECTSValue=2, CourseID=1, SemesterID=3, TeacherID=18},
                new Class{Name="Grafika Komputerowa", ECTSValue=2, CourseID=1, SemesterID=3, TeacherID=19},
                new Class{Name="Cyfrowe Przetwarzanie Sygnałów", ECTSValue=3, CourseID=1, SemesterID=3, TeacherID=20 },

                new Class{Name="Bezpieczeństwo Użytkowania Urządzeń", ECTSValue=1, CourseID=1, SemesterID=3, TeacherID=21},
                new Class{Name="Analogowe Przetwarzanie Sygnałów", ECTSValue=2, CourseID=1, SemesterID=3, TeacherID=4},
                new Class{Name="Zarządzanie Sieciami Komputerowymi", ECTSValue=3, CourseID=1, SemesterID=4, TeacherID=15},
                new Class{Name="Wychowanie Fizyczne", ECTSValue=1, CourseID=1, SemesterID=4, TeacherID=14},
                new Class{Name="Technika Mikroprocesorowa", ECTSValue=4, CourseID=1, SemesterID=4, TeacherID=11},

                new Class{Name="Systemy Elektromechaniczne", ECTSValue=1, CourseID=1, SemesterID=4, TeacherID=23},
                new Class{Name="Programowanie w Środowisku Sieciowym", ECTSValue=3, CourseID=1, SemesterID=4, TeacherID=2},
                new Class{Name="Programowanie Urządzeń Mobilnych", ECTSValue=5, CourseID=1, SemesterID=4, TeacherID=12},
                new Class{Name="Programowanie Wieloplatformowe", ECTSValue=4, CourseID=1, SemesterID=4, TeacherID=2},
                new Class{Name="Praktyka Zawodowa", ECTSValue=3, CourseID=1, SemesterID=4, TeacherID=17},

                new Class{Name="Metody Numeryczne", ECTSValue=3, CourseID=1, SemesterID=4, TeacherID=22},
                new Class{Name="Język Angielski", ECTSValue=2, CourseID=1, SemesterID=4, TeacherID=18},
                new Class{Name="Electromechanical Systems", ECTSValue=1, CourseID=1, SemesterID=4, TeacherID=23},
                new Class{Name="Sztuczna Inteligencja", ECTSValue=3, CourseID=1, SemesterID=5, TeacherID=20},
                new Class{Name="Systemy Elektromechaniczne", ECTSValue=3, CourseID=1, SemesterID=5, TeacherID=28},

                new Class{Name="System Elektroenergetyczny", ECTSValue=3, CourseID=1, SemesterID=5, TeacherID=24},
                new Class{Name="Serwisy Internetowe", ECTSValue=4, CourseID=1, SemesterID=5, TeacherID=30},
                new Class{Name="Programowanie Równoległe i Rozproszone", ECTSValue=4, CourseID=1, SemesterID=5, TeacherID=13},
                new Class{Name="Programowanie Mikrokontrolerów", ECTSValue=3, CourseID=1, SemesterID=5, TeacherID=29},
                new Class{Name="Język Angielski", ECTSValue=2, CourseID=1, SemesterID=5, TeacherID=18},

                new Class{Name="Energoelektronika", ECTSValue=2, CourseID=1, SemesterID=5, TeacherID=31},
                new Class{Name="Bazy Danych", ECTSValue=6, CourseID=1, SemesterID=5, TeacherID=34},
                new Class{Name="Analiza Algorytmów", ECTSValue=2, CourseID=1, SemesterID=5, TeacherID=13},

            };

            classes.ForEach(c => context.Class.Add(c));
            context.SaveChanges();
            List<Grade> grades = new List<Grade>
            {
                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=1},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=1},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=1},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=1},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=1},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=1},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=1},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=16,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=17,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=20,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=1},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=26,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=27,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=30,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=1},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=36,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=37,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=40,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=1},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=46,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=47,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=50,CourseID=1, StudentID=1},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=1},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=1},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=2},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=2},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=2},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=2},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=2},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=2},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=2},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=16,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=17,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=20,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=2},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=26,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=27,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=30,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=2},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=36,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=37,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=40,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=2},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=46,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=47,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=50,CourseID=1, StudentID=2},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=2},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=2},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=3},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=3},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=3},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=3},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=3},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=3},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=3},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=4},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=4},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=4},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=4},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=4},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=4},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=4},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=5},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=5},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=5},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=5},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=51,CourseID=1, StudentID=5},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=5},
                new Grade{Value=4.0F, ClassID=53,CourseID=1, StudentID=5},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=6},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=6},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=6},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=6},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=6},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=6},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=6},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=7},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=7},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=7},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=7},
                new Grade{Value=4.0F, ClassID=51,CourseID=1, StudentID=7},
                new Grade{Value=3.0F, ClassID=52,CourseID=1, StudentID=7},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=7},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=8},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=8},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=8},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=8},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=8},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=51,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=8},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=8},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=9},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=9},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=9},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=9},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=9},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=9},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=9},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=10},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=10},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=10},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=10},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=10},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=51,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=10},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=10},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=11},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=11},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=11},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=11},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=51,CourseID=1, StudentID=11},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=11},
                new Grade{Value=4.0F, ClassID=53,CourseID=1, StudentID=11},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=12},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=12},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=12},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=12},
                new Grade{Value=4.0F, ClassID=51,CourseID=1, StudentID=12},
                new Grade{Value=3.0F, ClassID=52,CourseID=1, StudentID=12},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=12},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=13},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=13},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=13},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=13},
                new Grade{Value=4.0F, ClassID=51,CourseID=1, StudentID=13},
                new Grade{Value=3.0F, ClassID=52,CourseID=1, StudentID=13},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=13},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=14},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=14},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=14},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=14},
                new Grade{Value=3.5F, ClassID=51,CourseID=1, StudentID=14},
                new Grade{Value=4.0F, ClassID=52,CourseID=1, StudentID=14},
                new Grade{Value=3.0F, ClassID=53,CourseID=1, StudentID=14},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=15},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=15},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=15},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=15},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=15},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=15},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=15},

                new Grade{Value=3.5F, ClassID=1,CourseID=1, StudentID=16},
                new Grade{Value=5.0F, ClassID=2,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=3,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=4,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=5,CourseID=1, StudentID=16},
                new Grade{Value=5.0F, ClassID=6,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=7,CourseID=1, StudentID=16},
                new Grade{Value=4.5F, ClassID=8,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=9,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=10,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=11,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=12,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=13,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=14,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=15,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=16,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=17,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=18,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=19,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=20,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=21,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=22,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=23,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=24,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=25,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=26,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=27,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=28,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=29,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=30,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=31,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=32,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=33,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=34,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=35,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=36,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=37,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=38,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=39,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=40,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=41,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=42,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=43,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=44,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=45,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=46,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=47,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=48,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=49,CourseID=1, StudentID=16},
                new Grade{Value=4.0F, ClassID=50,CourseID=1, StudentID=16},
                new Grade{Value=3.0F, ClassID=51,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=52,CourseID=1, StudentID=16},
                new Grade{Value=3.5F, ClassID=53,CourseID=1, StudentID=16},
            };

            grades.ForEach(g => context.Grade.Add(g));
            context.SaveChanges();
            List<Semester> semesters = new List<Semester>
            {
                new Semester{BeginningDate=new DateTime(2016,10,1),EndDate=new DateTime(2017,3,1)},
                new Semester{BeginningDate=new DateTime(2017,3,2),EndDate=new DateTime(2017,9,30)},
                new Semester{BeginningDate=new DateTime(2017,10,1),EndDate=new DateTime(2018,3,1)},
                new Semester{BeginningDate=new DateTime(2018,3,2),EndDate=new DateTime(2018,9,30)},
                new Semester{BeginningDate=new DateTime(2018,10,1),EndDate=new DateTime(2019,3,1)},
                new Semester{BeginningDate=new DateTime(2019,3,2),EndDate=new DateTime(2019,9,30)},
                new Semester{BeginningDate=new DateTime(2020,10,1),EndDate=new DateTime(2020,3,1)}
            };
            semesters.ForEach(s => context.Semester.Add(s));
            context.SaveChanges();
            List<Teacher> teachers = new List<Teacher>
            {
                new Teacher{FirstName="Marian", LastName="Hyla", Login="marhyl", Password="123"},
                new Teacher{FirstName="Artur", LastName="Pasierbek", Login="artpas", Password="123"},
                new Teacher{FirstName="Jerzy", LastName="Roj", Login="jerroj", Password="123"},
                new Teacher{FirstName="Stefan", LastName="Paszek", Login="stepas", Password="123"},
                new Teacher{FirstName="Roman", LastName="Rogozinski", Login="romrog", Password="123"},

                new Teacher{FirstName="Franciszek", LastName="Witos", Login="frawit", Password="123"},
                new Teacher{FirstName="Adam", LastName="Cichy", Login="adacic", Password="123"},
                new Teacher{FirstName="Andrzej", LastName="Kasperski", Login="andkas", Password="123"},
                new Teacher{FirstName="Piotr", LastName="Moska", Login="piomos", Password="123"},
                new Teacher{FirstName="Alicja", LastName="Samulewicz", Login="alisam", Password="123"},

                new Teacher{FirstName="Jerzy", LastName="Jakubiec", Login="jerjak", Password="123"},
                new Teacher{FirstName="Marcin", LastName="Polomski", Login="marpol", Password="123"},
                new Teacher{FirstName="Bozena", LastName="Wieczorek", Login="bozwie", Password="123"},
                new Teacher{FirstName="Boguslaw", LastName="Krzystanek", Login="bogkrz", Password="123"},
                new Teacher{FirstName="Beata", LastName="Krupanek", Login="beakru", Password="123"},

                new Teacher{FirstName="Henryk", LastName="Urzedniczok", Login="henurz", Password="123"},
                new Teacher{FirstName="Andrzej", LastName="Kowalik", Login="andkow", Password="123"},
                new Teacher{FirstName="Slawomir", LastName="Kajko", Login="slakaj", Password="123"},
                new Teacher{FirstName="Piotr", LastName="Zientek", Login="piozie", Password="123"},
                new Teacher{FirstName="Dariusz", LastName="Grabowski", Login="dargra", Password="123"},

                new Teacher{FirstName="Henryk", LastName="Kocot", Login="henkoc", Password="123"},
                new Teacher{FirstName="Bernard", LastName="Baron", Login="berbar", Password="123"},
                new Teacher{FirstName="Janusz", LastName="Burlikowski", Login="janbur", Password="123"},
                new Teacher{FirstName="Marcin", LastName="Niedopytalski", Login="marnie", Password="123"},
                new Teacher{FirstName="Jaroslaw", LastName="Michalak", Login="rafmic", Password="123"},

                new Teacher{FirstName="Anna", LastName="Piaskowy", Login="annpia", Password="123"},
                new Teacher{FirstName="Zbigniew", LastName="Kaczmarczyk", Login="zbikac", Password="123"},
                new Teacher{FirstName="Zygmunt", LastName="Kowalik", Login="zygkow", Password="123"},
                new Teacher{FirstName="Maciej", LastName="Sajkowski", Login="macsaj", Password="123"},

            };
            teachers.ForEach(t => context.Teacher.Add(t));
            context.SaveChanges();
        }
    }
}

